// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (user_id, name, url, created_at, updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, user_id, name, url, created_at, updated_at
`

type CreateFeedParams struct {
	UserID    uuid.UUID
	Name      string
	Url       string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.UserID,
		arg.Name,
		arg.Url,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeedDetails = `-- name: GetFeedDetails :many

SELECT u.name AS username, f.name AS feed_name, f.url  AS url
FROM users as u INNER JOIN feeds as f
ON f.user_id = u.id
`

type GetFeedDetailsRow struct {
	Username string
	FeedName string
	Url      string
}

func (q *Queries) GetFeedDetails(ctx context.Context) ([]GetFeedDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedDetailsRow
	for rows.Next() {
		var i GetFeedDetailsRow
		if err := rows.Scan(&i.Username, &i.FeedName, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetFeedTable = `-- name: ResetFeedTable :exec
DELETE FROM users
`

func (q *Queries) ResetFeedTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetFeedTable)
	return err
}
